= Python Practice (Day #5)
Jeff Thuong <jean-francois.thuong@ansys.com>
:icons: font
:experimental:
:sectnums:
:toc: left
:source-highlighter: pygments
:pygments-linenums-mode: inline
:pygments-style: manni
:source-language: python

== Challenge

* *Purpose*: Create a program doing data mining

The program will:

* Read from log of plane traffic leaving from an airport
* Generate a ranking of the flights and airlines based on take-off time

_4 files_:

* *airlines.py*: Description of class "*Airline*"   (c.f. details later)
* *processRecords.py*: Main program that processes data from input file to generate a report
* *report_Template.html*: Template for the html report generated by the program (*provided*)
* *test_airlines.py*: Unit tests (pytest) of your program (*provided*)

=== Description of input files

The input is a list of records of planes, with 1 record per line.

*Syntax*:
[source,csv]
	<date>, <time>,<code>, <airline>, <destination>, <take-off>

With:
.Data in records
[%header,cols="3"]
|===
^|Field ^|Description ^|Example

^|<date>
^|Date of the flight in format `YYYY-MM-DD`
^|2015-08-21

^|<time>
^|Planned departure time (hh:mm)
^|13:10

^|<code>
^|Code of the flight
^|AF117

^|<airline>
^|Name of the airline
^|Air France

^|<destination>
^|Name of the destination airport
^|Nagoya Intl Airport

^|<take-off>
^|Real Time of take off (hh:mm)
^|19:25
|===

__Example__:
[source]
2015-08-21, 10:20, AF117, Air France, Paris Ch. de Gaulle, 11:20
2015-08-21, 10:30, 9C8601, China Spring Airlines, Nagoya Intl Airport, 12:35
2015-08-21, 10:35, CA155, China International Airlines, Sendai, 13:30

=== Class *Airline* (_airline.py_)

*4 attributes*:

* "*name*" (e.g. "Air France")
* "*code*" made of 2 letters (e.g. "AF")
* "*flights*": dictionary, key="code flight", value = list of take-off records +
  _Example_: +
+
[source]
----
{
    'AF123': [
        {'date':"2018-02-29", 'time':"12:13", "delay":45},
        {'date':"2018-02-30", 'time':"12:13", "delay":15}
    ]
}
----
+
NOTE: A record is a dictionary with 3 keys: *date*, *time* (expected), *delay*
* "*destination*": dictionary with key = "code flight", value = "destination airport" +
  _Example_: `{'AF123': "Paris Orly"}`
+
NOTE: `delay` = <take-off> - <time> (measured in *minutes*)


{blank}

TIP: We recommend to create a function `get_delay` to compute the delay (in minutes).

{blank}

*3 methods*:

* *add_info*: add flight information (dictionary) and store in attributes `flights` and `destination`. +
  Create flight if it does not exist +
  Prototype: `add_info(self, info) -> None  # info is a dictionary`
* *get_rating_flight*: return tuple (*% late*, *average delay*) for a flight +
  Prototype: `get_rating_flight(self, flight_code:str) -> Tuple[int, int]`
* *get_rating_airline*: return tuple (*% late*, *average delay*) for airline +
  Prototype: `get_rating_airline(self) -> Tuple[int, int]`

[NOTE]
====

1. `% late` = number flights with delay > 30 min / number of flights, saved as integer
2. `average delay` = sum of delay for departure / number of flights, saved as integer
====

=== Main Program (_processRecords.py_)

Function `read_flight_records`:

* _Input_: input file name
* _Output_: list of take off records, each element is a dictionary with following keys: +
   *date*, *time*, *code*, *airline*, *destination*, and *take-off*


Function `get_ratings_airlines`:

* _Input_: list of landing records returned by `read_flight_records`
* _Output_: dictionary with key=airline name, value=Object of class *Airline* with all the records of that airline


Function `list_sorted_ratings`:

* _Input_: dictionary returned by `get_ratings_airlines`
* _Output_: 2 lists sorted based on "% late" (lowest % first)
+
1. list of tuples (<airline>, <% late>, <average delay>) for each airline
2. list of tuples (<code>, <% late>, <average delay>) for each flight

NOTE: all the results shall be integers


Function `get_first_last_elem`:

* _Input_:
+
1. `<list_ranking>`
2. `<nb_elem>` (number of elements)
* _Output_: 2 lists with first and last `<nb_elem>` elements

.get_first_last_elem
[source]
----
>>> get_first_last_elem(['a', 'b', 'c', 'd', 'e'], 2)
(['a','b'], ['e', 'd'])  # <1>
----
<1> Notice that the last elements shall be in reversed order (i.e. starting from last element)  


*Main function*:

* Parse arguments based on following usage:
+
====
		processRecords.py <input file> [(-o|--output) <report file>] [-n <nb_ranking>]
====
NOTE: default value of `<nb_ranking>` is 10
* Read data from the input file with function `read_flight_records`
* Create dictionary of airlines with function `get_ratings_airlines`
* Sort airlines and flights with function `list_sorted_ratings`
* Generate a report (by using function `get_first_last_elem`) with:
 - List of <nb_ranking> best airlines based on chances to be late
 - List of <nb_ranking> best flights based on chances to be late
 - List of <nb_ranking> worse airlines based on chances to be late
 - List of <nb_ranking> worse flights based on chances to be late


== Airline Class

.airlines.py
[source]
----
include::Solution/level_FINAL/airlines_tmp.py[]
----

== Test Airline

.test_airlines.py
[source]
----
include::Solution/level_FINAL/test_airlines.py[]
----
